server:
  servlet:
    context-path: /card-service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}/postgres
    username: postgres
    password: postgres
  cloud:
    gcp:
      project-id: sample1-424312
      sql:
        instance-connection-name: sample1-424312:us-central1:test-postgres-cloud-sql
        database-name: postgres
  jpa:
    hibernate:
      ddl-auto: update